"""Platform-independent P0 mandatory ED reference contracts."""

from .bandwidth import BandwidthEstimate, BandwidthEstimator, BandwidthProfile
from .channelizer import ChannelizedFrame, P0Channelizer, P0ChannelizerProfile
from .direct_frame import DirectP0FrameAdapter, DirectP0Profile
from .native_channelizer import (
    NativeP0Channelizer,
    create_realtime_channelizer,
    find_native_channelizer_library,
    native_channelizer_cpu_supported,
)
from .coarse_detection import (
    CoarseDetection,
    CoarseDetectionConfig,
    CoarseDetectionFrame,
    CoarseSpectrumDetector,
)
from .detection import (
    P0_DETECTOR_PROFILE,
    OSCFARConfig,
    OSCFARDetector,
    OSCFARFrameResult,
    MultiscaleDetector,
    MultiscaleFrameResult,
    P0DetectorProfile,
    derive_os_cfar_threshold_coefficient,
    order_statistic_expected_ratio,
    os_cfar_false_alarm_probability,
    P0_WIDEBAND_RECOVERY_PROFILE,
    WidebandRecoveryConfig,
)
from .df import (
    DFEstimate,
    DFMeasurement,
    DFProfile,
    FIELD_AMPLITUDE_DF_PROFILE,
    LEGACY_AMPLITUDE_DF_PROFILE,
    ManualAmplitudeDF,
)
from .adaptive_df import (
    AdaptiveDFObservation,
    AdaptiveDirectionSweep,
    COARSE_STEP_DEG,
    REFINEMENT_RADIUS_DEG,
    REFINEMENT_STEP_DEG,
)
from .direction_client import BoardDFEstimate, decode_df_response, encode_df_request, estimate_on_board
from .two_point_df import REAL_TWO_POINT_SOURCE, TwoPointDFResult, TwoPointPower, analyze_two_point_hackrf_df
from .field_df import AntennaReference, LocationFix, PositionSource, geographic_bearing_from_manual_reference
from .recorded_df import (
    RECORDED_DF_SOURCE,
    RecordedDFError,
    RecordedDFPoint,
    RecordedDFReport,
    analyze_recorded_df,
    write_recorded_df_report,
)
from .map_direction import (
    DirectionPresentation,
    GeographicLOB,
    SensorPosition,
    build_direction_presentation,
    destination_point,
    geographic_lob_geometry,
    normalize_bearing_deg,
)
from .models import CandidateRegion, P0ParameterResult, Provenance
from .parameters import ParameterExtractor, ParameterProfile
from .search import (
    P0SearchEngine,
    ReplaySearchBackend,
    SearchAcquisitionBackend,
    SearchExecutionResult,
    SearchMode,
    SearchRequest,
    TuningWindow,
)
from .hackrf_search import (
    HackRFSearchPlanner,
    HackRFTuningPlan,
    HackRFTuningProfile,
    HackRFTuningWindowPlan,
    shifted_absolute_frequency_axis,
)
from .temporal import TemporalConfirmation, TrackedCandidate
from .transport import (
    BoundedIQQueue,
    IQFrame,
    IQFrameCodec,
    IQCapabilityCodec,
    IQResponse,
    IQResponseCodec,
    IQTransport,
    LocalEDResponse,
    InlineParameterField,
    InlineParameterResult,
    ParameterObservationRequest,
    LoopbackIQTransport,
    TCPClientIQTransport,
    TransportError,
    TransportStats,
    TransportCapabilities,
    decode_local_ed_response,
)

__all__ = [
    "BoundedIQQueue",
    "BandwidthEstimate",
    "BandwidthEstimator",
    "BandwidthProfile",
    "AntennaReference",
    "AdaptiveDFObservation",
    "AdaptiveDirectionSweep",
    "CandidateRegion",
    "COARSE_STEP_DEG",
    "ChannelizedFrame",
    "CoarseDetection",
    "CoarseDetectionConfig",
    "CoarseDetectionFrame",
    "CoarseSpectrumDetector",
    "DFEstimate",
    "DFMeasurement",
    "DFProfile",
    "FIELD_AMPLITUDE_DF_PROFILE",
    "LEGACY_AMPLITUDE_DF_PROFILE",
    "LocationFix",
    "DirectionPresentation",
    "GeographicLOB",
    "build_direction_presentation",
    "analyze_recorded_df",
    "IQFrame",
    "IQFrameCodec",
    "IQCapabilityCodec",
    "IQResponse",
    "IQResponseCodec",
    "IQTransport",
    "LocalEDResponse",
    "InlineParameterField",
    "InlineParameterResult",
    "LoopbackIQTransport",
    "ManualAmplitudeDF",
    "BoardDFEstimate",
    "decode_df_response",
    "encode_df_request",
    "estimate_on_board",
    "REAL_TWO_POINT_SOURCE",
    "TwoPointDFResult",
    "TwoPointPower",
    "analyze_two_point_hackrf_df",
    "RECORDED_DF_SOURCE",
    "REFINEMENT_RADIUS_DEG",
    "REFINEMENT_STEP_DEG",
    "RecordedDFError",
    "RecordedDFPoint",
    "RecordedDFReport",
    "OSCFARConfig",
    "OSCFARDetector",
    "OSCFARFrameResult",
    "MultiscaleDetector",
    "MultiscaleFrameResult",
    "P0DetectorProfile",
    "P0_DETECTOR_PROFILE",
    "P0_WIDEBAND_RECOVERY_PROFILE",
    "PositionSource",
    "P0ParameterResult",
    "ParameterObservationRequest",
    "P0Channelizer",
    "P0ChannelizerProfile",
    "NativeP0Channelizer",
    "create_realtime_channelizer",
    "DirectP0FrameAdapter",
    "DirectP0Profile",
    "find_native_channelizer_library",
    "native_channelizer_cpu_supported",
    "P0SearchEngine",
    "ParameterExtractor",
    "ParameterProfile",
    "Provenance",
    "ReplaySearchBackend",
    "SearchAcquisitionBackend",
    "SearchExecutionResult",
    "SearchMode",
    "SearchRequest",
    "SensorPosition",
    "HackRFSearchPlanner",
    "HackRFTuningPlan",
    "HackRFTuningProfile",
    "HackRFTuningWindowPlan",
    "shifted_absolute_frequency_axis",
    "TransportError",
    "TransportStats",
    "TransportCapabilities",
    "decode_local_ed_response",
    "TemporalConfirmation",
    "TCPClientIQTransport",
    "TrackedCandidate",
    "TuningWindow",
    "WidebandRecoveryConfig",
    "derive_os_cfar_threshold_coefficient",
    "destination_point",
    "geographic_lob_geometry",
    "geographic_bearing_from_manual_reference",
    "order_statistic_expected_ratio",
    "os_cfar_false_alarm_probability",
    "normalize_bearing_deg",
    "write_recorded_df_report",
]
