"""Platform-independent P0 mandatory ED reference contracts."""

from .bandwidth import BandwidthEstimate, BandwidthEstimator, BandwidthProfile
from .detection import (
    P0_DETECTOR_PROFILE,
    OSCFARConfig,
    OSCFARDetector,
    OSCFARFrameResult,
    P0DetectorProfile,
    derive_os_cfar_threshold_coefficient,
    order_statistic_expected_ratio,
    os_cfar_false_alarm_probability,
)
from .df import DFEstimate, DFMeasurement, ManualAmplitudeDF
from .two_point_df import REAL_TWO_POINT_SOURCE, TwoPointDFResult, TwoPointPower, analyze_two_point_hackrf_df
from .field_df import AntennaReference, LocationFix, PositionSource, geographic_bearing_from_manual_reference
from .recorded_df import (
    RECORDED_DF_SOURCE,
    RecordedDFError,
    RecordedDFPoint,
    RecordedDFReport,
    analyze_recorded_df,
    write_recorded_df_report,
)
from .map_direction import (
    DirectionPresentation,
    GeographicLOB,
    SensorPosition,
    build_direction_presentation,
    destination_point,
    geographic_lob_geometry,
    normalize_bearing_deg,
)
from .models import CandidateRegion, P0ParameterResult, Provenance
from .parameters import ParameterExtractor, ParameterProfile
from .search import (
    P0SearchEngine,
    ReplaySearchBackend,
    SearchAcquisitionBackend,
    SearchExecutionResult,
    SearchMode,
    SearchRequest,
    TuningWindow,
)
from .hackrf_search import (
    HackRFSearchBackend,
    HackRFSearchPlanner,
    HackRFTuningPlan,
    HackRFTuningProfile,
    HackRFTuningWindowPlan,
    shifted_absolute_frequency_axis,
)
from .temporal import TemporalConfirmation, TrackedCandidate
from .transport import (
    BoundedIQQueue,
    IQFrame,
    IQFrameCodec,
    IQTransport,
    LoopbackIQTransport,
    TCPClientIQTransport,
    TransportError,
    TransportStats,
)

__all__ = [
    "BoundedIQQueue",
    "BandwidthEstimate",
    "BandwidthEstimator",
    "BandwidthProfile",
    "AntennaReference",
    "CandidateRegion",
    "DFEstimate",
    "DFMeasurement",
    "LocationFix",
    "DirectionPresentation",
    "GeographicLOB",
    "build_direction_presentation",
    "analyze_recorded_df",
    "IQFrame",
    "IQFrameCodec",
    "IQTransport",
    "LoopbackIQTransport",
    "ManualAmplitudeDF",
    "REAL_TWO_POINT_SOURCE",
    "TwoPointDFResult",
    "TwoPointPower",
    "analyze_two_point_hackrf_df",
    "RECORDED_DF_SOURCE",
    "RecordedDFError",
    "RecordedDFPoint",
    "RecordedDFReport",
    "OSCFARConfig",
    "OSCFARDetector",
    "OSCFARFrameResult",
    "P0DetectorProfile",
    "P0_DETECTOR_PROFILE",
    "PositionSource",
    "P0ParameterResult",
    "P0SearchEngine",
    "ParameterExtractor",
    "ParameterProfile",
    "Provenance",
    "ReplaySearchBackend",
    "SearchAcquisitionBackend",
    "SearchExecutionResult",
    "SearchMode",
    "SearchRequest",
    "SensorPosition",
    "HackRFSearchBackend",
    "HackRFSearchPlanner",
    "HackRFTuningPlan",
    "HackRFTuningProfile",
    "HackRFTuningWindowPlan",
    "shifted_absolute_frequency_axis",
    "TransportError",
    "TransportStats",
    "TemporalConfirmation",
    "TCPClientIQTransport",
    "TrackedCandidate",
    "TuningWindow",
    "derive_os_cfar_threshold_coefficient",
    "destination_point",
    "geographic_lob_geometry",
    "geographic_bearing_from_manual_reference",
    "order_statistic_expected_ratio",
    "os_cfar_false_alarm_probability",
    "normalize_bearing_deg",
    "write_recorded_df_report",
]
