"""User-visible Turkish text catalog for the permanent operation console."""

TURKISH_GLYPHS = "çÇğĞıİöÖşŞüÜ"

TEXT = {
    "window_title": "TEKNOFEST Elektronik Harp Operatör Konsolu",
    "application_title": "Spektrum, Tespit ve Parametre İnceleme",
    "open_sigmf": "SigMF Aç",
    "source_type": "Kaynak Türü",
    "source_sigmf": "SigMF Kaydı",
    "source_hackrf": "HackRF Canlı RX",
    "source_deterministic": "Deterministik Test Kaynağı",
    "open_test_source": "Test Kaynağını Aç",
    "no_source": "Veri kaynağı seçilmedi",
    "opening_source": "Kaynak açılıyor…",
    "source": "Veri Kaynağı",
    "metadata": "Kayıt Bilgileri",
    "center_frequency": "Merkez Frekansı",
    "sample_rate": "Örnekleme Hızı",
    "datatype": "Veri Türü",
    "frame_length": "Çerçeve Uzunluğu",
    "frame_position": "Çerçeve Konumu",
    "channel": "Kanal",
    "start": "Başlat",
    "pause": "Duraklat",
    "stop": "Durdur",
    "review_speed": "İnceleme Hızı",
    "axis": "Frekans Ekseni",
    "axis_offset": "Merkeze göre (MHz)",
    "axis_absolute": "Mutlak frekans (MHz)",
    "display": "Gösterim",
    "bin_power": "Bin/ton gücü (dBFS/bin)",
    "psd": "Güç spektral yoğunluğu (dBFS/Hz)",
    "remove_dc": "DC'yi gider",
    "average": "Üstel ortalama (α=0,2)",
    "detection_layer": "Tespit katmanını göster",
    "pfa": "Teorik Pfa/CUT",
    "evaluate_center": "Merkez hücresini değerlendir",
    "detections": "Tespitler",
    "no_detection": "Tespit yok",
    "profile": "Aktif İşlem Profili",
    "validated_envelope": "Doğrulanmış parametre zarfı",
    "tentative": "Geçici",
    "confirmed": "Doğrulanmış",
    "ended": "Sona ermiş",
    "detection_detail": "Kaba aday bölgeler kesin bant genişliği değildir.",
    "core_parameters": "Çekirdek Parametreler",
    "no_parameter": "Doğrulanmış olay parametresi yok",
    "parameter_event": "Olay #{event_id} · frame-local kestirim",
    "estimated_frequency": "Frekans",
    "estimated_bandwidth": "Bant Genişliği",
    "relative_power": "Göreli Güç",
    "in_band_snr": "Bant İçi SNR",
    "signal_domain": "Sinyal Alanı",
    "observed_carrier": "Gözlenmiş taşıyıcı",
    "spectral_center": "Spektral merkez",
    "not_observed": "Gözlenmedi",
    "not_applicable": "Uygulanamaz",
    "insufficient_quality": "Kalite yetersiz",
    "uncertain": "Belirsiz",
    "phase04_fallback": "PHASE-04 doğrulama bağı geçersiz; parametre çıkarımı kapalı, PHASE-03 tespit profili kullanılıyor.",
    "instant_detection_note": "Tespit anlık lineer gücü kullanır; spektrum ortalaması yalnız gösterimdir.",
    "candidate_limit": "Aday kapasitesi aşıldı; {count} aday izlenemedi.",
    "history_evicted": "{count} eski olay geçmişten çıkarıldı.",
    "events_hidden": "{count} olay daha gösterilmiyor.",
    "profile_error": "Doğrulanmış işlem profili yüklenemedi.",
    "parameter_error": "Ayar doğrulanmış profil sınırları dışında.",
    "ready": "Hazır",
    "playing": "Oynatılıyor",
    "paused": "Duraklatıldı",
    "stopped": "Durduruldu",
    "empty": "Kayıt seçilmedi.",
    "empty_spectrum": "Spektrum görüntülemek için bir veri kaynağı seçin.",
    "empty_history": "İşlenmiş çerçeve geçmişi yok.",
    "uncalibrated": "Güç değerleri kalibre edilmemiş dBFS sonuçlarıdır; dBm değildir.",
    "spectrum": "Spektrum",
    "waterfall": "Spektrum Geçmişi",
    "frequency": "Frekans",
    "center_offset": "Merkez Ofseti",
    "history_frame": "Geçmiş Çerçeve",
    "select_metadata": "SigMF metadata dosyasını seçin",
    "select_data": "Bu metadata için SigMF data dosyasını seçin",
    "file_filter": "SigMF metadata (*.sigmf-meta *.sigmf-meta.txt);;JSON ve metin (*.json *.txt);;Tüm dosyalar (*)",
    "data_filter": "SigMF data (*.sigmf-data *.bin);;Tüm dosyalar (*)",
    "source_error": "Veri kaynağı açılamadı.",
    "processing_error": "Çerçeve işlenemedi.",
    "warning_default_channel": "Kanal sayısı metadata'da yok; SigMF varsayılanı olan tek kanal kullanılıyor.",
    "warning_nonstandard_name": "Metadata standart SigMF uzantısını kullanmıyor; data dosyası açıkça seçildi.",
    "warning_partial_frame": "Eksik son çerçeve işleme dışında bırakıldı.",
    "operation_workspace": "Operasyon",
    "analysis_workspace": "Sinyal Analizi",
    "listening_workspace": "Dinleme",
    "listening_select_event": "Dinleme için doğrulanmış bir olay seçin.",
    "demodulation": "Demodülasyon",
    "nfm": "Dar Bant FM (NFM)",
    "listening_offset": "Merkez Ofseti",
    "listening_bandwidth": "Kanal Bant Genişliği",
    "volume": "Ses Seviyesi",
    "prepare_listening": "Hazırla",
    "play_audio": "Oynat",
    "pause_audio": "Duraklat",
    "stop_audio": "Durdur",
    "export_wav": "WAV Dışa Aktar",
    "listening_not_prepared": "Dinleme hazırlanmadı.",
    "listening_preparing": "Dört ardışık çerçeve hazırlanıyor…",
    "listening_ready": "48 kHz mono ses hazır · baskın ton {tone_hz} Hz",
    "listening_failed": "Dinleme hazırlanamadı.",
    "audio_backend_pending": "Ses çıkışı denetleniyor.",
    "audio_backend_ready": "Ses çıkışı kullanılabilir; WAV dışa aktarma da etkindir.",
    "audio_backend_unavailable": "Ses çıkışı kullanılamıyor; WAV dışa aktarma çalışmaya devam eder.",
    "fixture_not_live": "Deterministik test kaynağı — canlı RF değildir.",
    "wav_saved": "WAV dosyası kaydedildi.",
    "wav_filter": "WAV ses (*.wav)",
    "analysis_spectrum": "Seçili Olay Spektrumu",
    "select_confirmed_event": "Analiz için doğrulanmış bir olay seçin.",
    "no_analysis_span": "Analiz aralığı seçilmedi.",
    "auto_suggested": "Otomatik öneri",
    "operator_adjusted": "Operatör ayarı",
    "start_measurement": "Ölçümü Başlat",
    "clear_measurement": "Temizle",
    "measurement_not_started": "Ölçüm başlatılmadı.",
    "measurement_running": "Dört ardışık çerçeve ölçülüyor…",
    "measurement_complete": "Kalite kontrollü ölçüm tamamlandı.",
    "measurement_failed": "Ölçülemedi",
    "not_validated": "Henüz doğrulanmadı",
    "neighbor_overlap": "Analiz aralığı komşu doğrulanmış olayla çakışıyor.",
    "event_ownership_lost": "Olay sahipliği dört çerçeve boyunca korunmadı.",
    "stale_generation": "Ölçüm isteği artık geçerli olmayan bir yapılandırmaya ait.",
    "obw_temporal_instability": "Bant kenarları dört çerçevede kararlı değil.",
    "carrier_line_absent": "Taşıyıcı çizgisi için yeterli kanıt yok.",
    "classification_ambiguous": "Analog/sayısal ayrımı için kanıt belirsiz.",
    "emission_center": "Yayın Merkez Frekansı",
    "carrier_line": "Taşıyıcı Çizgisi Frekansı",
    "lower_band_edge": "Alt Bant Sınırı",
    "upper_band_edge": "Üst Bant Sınırı",
    "occupied_bandwidth": "İşgal Edilen Bant Genişliği (%99 güç)",
    "peak_power": "Tepe Gücü",
    "channel_power": "Kanal Gücü",
    "quality_not_available": "Kalite değerlendirmesi yok.",
    "quality_passed": "Kalite kapıları geçti.",
    "uncalibrated_e1": "Kalibrasyon yapılmadı; değerler dBFS ölçeğindedir.",
    "manual_span_available": "Otomatik aralık kullanılamadı; operatör aralığı elle seçebilir.",
    "e1_fallback": "PHASE-04-E1 doğrulama bağı geçersiz; parametre ölçümü kapalı, PHASE-03 tespit profili kullanılıyor.",
    "span_edge_clipping": "Analiz aralığı sinyal enerjisini sınırlıyor.",
    "reference_power_mismatch": "Sol ve sağ gürültü referansları uyumsuz.",
    "reference_cells_unavailable": "Yeterli gürültü referans hücresi yok.",
    "insufficient_excess_power": "Sinyal gücü kalite eşiğinin altında.",
    "temporal_edges_unstable": "Bant sınırları dört çerçevede kararlı değil.",
    "four_consecutive_frames_required": "Dört ardışık çerçeve bulunamadı.",
    "hackrf_controls": "HackRF-1 RX Hazırlığı",
    "hackrf_tools_missing": "HackRF araçları bulunamadı",
    "hackrf_device_missing": "HackRF cihazı bulunamadı",
    "hardware_acceptance_pending": "Donanım kabul testi bekleniyor",
    "live_rx_unavailable": "Canlı alım kullanılamıyor",
    "device_searching": "Cihaz aranıyor…",
    "device_ready": "Cihaz hazır",
    "sweep_running": "Tarama yapılıyor…",
    "capture_starting": "Alım başlatılıyor…",
    "live_capture": "Canlı alım",
    "capture_stopped": "Alım durduruldu",
    "device_disconnected": "Cihaz bağlantısı kesildi",
    "operation_timeout": "İşlem zaman aşımına uğradı",
    "refresh_hardware": "Araçları ve Cihazı Denetle",
    "start_capture": "Alımı Başlat",
    "stop_capture": "Alımı Durdur",
    "center_frequency_mhz": "Merkez (MHz)",
    "sample_rate_msps": "Örnekleme (MS/s)",
    "rf_amplifier": "RF yükselteci",
    "lna_gain": "IF/LNA (dB)",
    "vga_gain": "Baseband/VGA (dB)",
    "deterministic_source_active": "Deterministik test kaynağı etkin; canlı RF değildir.",
    "hackrf_cli_error": "HackRF aracı kontrollü bir hatayla sonlandı.",
}


ERROR_TEXT = {
    "metadata_not_found": "Metadata dosyası bulunamadı.",
    "metadata_invalid_utf8": "Metadata geçerli UTF-8 değil.",
    "metadata_invalid_json": "Metadata geçerli JSON değil.",
    "unsupported_core_version": "SigMF sürümü bu aşamada desteklenmiyor.",
    "unsupported_datatype": "SigMF veri türü desteklenmiyor.",
    "unsupported_channel_count": "Yalnız tek kanallı kayıtlar destekleniyor.",
    "unsupported_capture_count": "Bu aşamada tam olarak bir capture destekleniyor.",
    "invalid_capture_start": "Capture karmaşık örnek sıfırdan başlamalıdır.",
    "data_path_required": "Standard dışı metadata için data dosyası seçilmelidir.",
    "data_not_found": "SigMF data dosyası bulunamadı.",
    "malformed_iq_pair": "Data dosyası eksik bir I/Q örneğiyle bitiyor.",
    "frame_read_failed": "Seçilen çerçeve data dosyasından okunamadı.",
    "short_frame_read": "Data kaynağı tam çerçeve döndürmedi.",
    "frame_index_out_of_range": "Çerçeve konumu kayıt sınırının dışında.",
    "profile_unreadable": "Doğrulanmış işlem profili okunamadı.",
    "profile_not_validated": "Operasyon ekranı yalnız doğrulanmış işlem profili kullanır.",
    "parameter_outside_validated_envelope": "Ayar doğrulanmış profil sınırları dışında.",
    "power_size_mismatch": "Detector giriş gücü beklenen 4096 hücreyi içermiyor.",
    "nonfinite_power": "Detector girişinde sonlu olmayan güç değeri bulundu.",
    "negative_power": "Detector girişinde negatif güç değeri bulundu.",
    "parameter_bounds_invalid": "Parametre çıkarımı bellek veya guard sınırını ihlal ediyor.",
    "comparison_binding_required": "PHASE-04 karşılaştırma bağı doğrulanamadı.",
    "comparison_binding_mismatch": "PHASE-04 profili karşılaştırma kanıtıyla eşleşmiyor.",
    "tools_unavailable": "HackRF araçları bulunamadı.",
    "device_not_found": "HackRF cihazı bulunamadı.",
    "device_output_unrecognized": "HackRF cihaz bilgisi güvenle çözümlenemedi.",
    "cli_options_unverified": "HackRF yardım çıktısında gerekli RX seçenekleri doğrulanmadı.",
    "capture_process_failed": "HackRF capture aracı başarısız oldu.",
    "short_capture": "Capture beklenen örnek sayısından kısa.",
    "long_capture": "Capture beklenen örnek sayısından uzun.",
    "operation_cancelled": "HackRF işlemi iptal edildi.",
    "operation_timeout": "HackRF işlemi zaman aşımına uğradı.",
    "process_start_failed": "HackRF aracı başlatılamadı.",
    "device_probe_failed": "HackRF cihaz denetimi tamamlanamadı.",
    "unsupported_demodulation": "Yalnız AM ve Dar Bant FM demodülasyonu desteklenir.",
    "invalid_sample_rate": "Kaynak örnekleme hızı dinleme için geçersiz.",
    "invalid_channel_bandwidth": "Kanal bant genişliği desteklenen sınırın dışında.",
    "nyquist_limit": "Seçilen kanal kaynak Nyquist sınırını aşıyor.",
    "insufficient_iq": "Dinleme için dört tam ardışık I/Q çerçevesi bulunamadı.",
    "short_iq_frame": "Dinleme kaynağı tam 4096 örnekli çerçeve döndürmedi.",
    "nonfinite_iq": "I/Q örneklerinde geçersiz sayısal değer bulundu.",
    "insufficient_audio": "Seçilen kanaldan yeterli sonlu ses üretilemedi.",
    "stale_listening_result": "Dinleme sonucu artık geçerli olmayan kaynak veya olaya ait.",
    "wav_write_failed": "WAV dosyası kaydedilemedi.",
}
