"""User-visible Turkish text catalog for the permanent operation console."""

TURKISH_GLYPHS = "çÇğĞıİöÖşŞüÜ"

TEXT = {
    "window_title": "TEKNOFEST Elektronik Harp Operatör Konsolu",
    "application_title": "Spektrum ve Tespit İnceleme",
    "open_sigmf": "SigMF Aç",
    "no_source": "Veri kaynağı seçilmedi",
    "opening_source": "Kaynak açılıyor…",
    "source": "Veri Kaynağı",
    "metadata": "Kayıt Bilgileri",
    "center_frequency": "Merkez Frekansı",
    "sample_rate": "Örnekleme Hızı",
    "datatype": "Veri Türü",
    "frame_length": "Çerçeve Uzunluğu",
    "frame_position": "Çerçeve Konumu",
    "channel": "Kanal",
    "start": "Başlat",
    "pause": "Duraklat",
    "stop": "Durdur",
    "review_speed": "İnceleme Hızı",
    "axis": "Frekans Ekseni",
    "axis_offset": "Merkeze göre (MHz)",
    "axis_absolute": "Mutlak frekans (MHz)",
    "display": "Gösterim",
    "bin_power": "Bin/ton gücü (dBFS/bin)",
    "psd": "Güç spektral yoğunluğu (dBFS/Hz)",
    "remove_dc": "DC'yi gider",
    "average": "Üstel ortalama (α=0,2)",
    "detection_layer": "Tespit katmanını göster",
    "pfa": "Teorik Pfa/CUT",
    "evaluate_center": "Merkez hücresini değerlendir",
    "detections": "Tespitler",
    "no_detection": "Tespit yok",
    "profile": "Aktif İşlem Profili",
    "validated_envelope": "Doğrulanmış parametre zarfı",
    "tentative": "Geçici",
    "confirmed": "Doğrulanmış",
    "ended": "Sona ermiş",
    "detection_detail": "Kaba aday bölgeler kesin bant genişliği değildir.",
    "instant_detection_note": "Tespit anlık lineer gücü kullanır; spektrum ortalaması yalnız gösterimdir.",
    "candidate_limit": "Aday kapasitesi aşıldı; {count} aday izlenemedi.",
    "history_evicted": "{count} eski olay geçmişten çıkarıldı.",
    "events_hidden": "{count} olay daha gösterilmiyor.",
    "profile_error": "Doğrulanmış işlem profili yüklenemedi.",
    "parameter_error": "Ayar doğrulanmış profil sınırları dışında.",
    "ready": "Hazır",
    "playing": "Oynatılıyor",
    "paused": "Duraklatıldı",
    "stopped": "Durduruldu",
    "empty": "Kayıt seçilmedi.",
    "empty_spectrum": "Spektrum görüntülemek için bir SigMF kaydı açın.",
    "empty_history": "İşlenmiş çerçeve geçmişi yok.",
    "uncalibrated": "Güç değerleri kalibre edilmemiş dBFS sonuçlarıdır; dBm değildir.",
    "spectrum": "Spektrum",
    "waterfall": "Spektrum Geçmişi",
    "frequency": "Frekans",
    "center_offset": "Merkez Ofseti",
    "history_frame": "Geçmiş Çerçeve",
    "select_metadata": "SigMF metadata dosyasını seçin",
    "select_data": "Bu metadata için SigMF data dosyasını seçin",
    "file_filter": "SigMF metadata (*.sigmf-meta *.sigmf-meta.txt);;JSON ve metin (*.json *.txt);;Tüm dosyalar (*)",
    "data_filter": "SigMF data (*.sigmf-data *.bin);;Tüm dosyalar (*)",
    "source_error": "Veri kaynağı açılamadı.",
    "processing_error": "Çerçeve işlenemedi.",
    "warning_default_channel": "Kanal sayısı metadata'da yok; SigMF varsayılanı olan tek kanal kullanılıyor.",
    "warning_nonstandard_name": "Metadata standart SigMF uzantısını kullanmıyor; data dosyası açıkça seçildi.",
    "warning_partial_frame": "Eksik son çerçeve işleme dışında bırakıldı.",
}


ERROR_TEXT = {
    "metadata_not_found": "Metadata dosyası bulunamadı.",
    "metadata_invalid_utf8": "Metadata geçerli UTF-8 değil.",
    "metadata_invalid_json": "Metadata geçerli JSON değil.",
    "unsupported_core_version": "SigMF sürümü bu aşamada desteklenmiyor.",
    "unsupported_datatype": "SigMF veri türü desteklenmiyor.",
    "unsupported_channel_count": "Yalnız tek kanallı kayıtlar destekleniyor.",
    "unsupported_capture_count": "Bu aşamada tam olarak bir capture destekleniyor.",
    "invalid_capture_start": "Capture karmaşık örnek sıfırdan başlamalıdır.",
    "data_path_required": "Standard dışı metadata için data dosyası seçilmelidir.",
    "data_not_found": "SigMF data dosyası bulunamadı.",
    "malformed_iq_pair": "Data dosyası eksik bir I/Q örneğiyle bitiyor.",
    "frame_read_failed": "Seçilen çerçeve data dosyasından okunamadı.",
    "short_frame_read": "Data kaynağı tam çerçeve döndürmedi.",
    "frame_index_out_of_range": "Çerçeve konumu kayıt sınırının dışında.",
    "profile_unreadable": "Doğrulanmış işlem profili okunamadı.",
    "profile_not_validated": "Operasyon ekranı yalnız doğrulanmış işlem profili kullanır.",
    "parameter_outside_validated_envelope": "Ayar doğrulanmış profil sınırları dışında.",
    "power_size_mismatch": "Detector giriş gücü beklenen 4096 hücreyi içermiyor.",
    "nonfinite_power": "Detector girişinde sonlu olmayan güç değeri bulundu.",
    "negative_power": "Detector girişinde negatif güç değeri bulundu.",
}
