module phase06h_candidate_synthesis_top (
  input  logic        aclk,
  input  logic        aresetn,
  input  logic        s_axis_tvalid,
  output logic        s_axis_tready,
  input  logic [57:0] s_axis_tdata,
  input  logic        s_axis_tlast,
  input  logic [11:0] s_axis_tuser_natural_index,
  input  logic [11:0] s_axis_tuser_shifted_index,
  input  logic [58:0] s_axis_tuser_median_twice,
  input  logic [57:0] s_axis_tuser_noise,
  input  logic [61:0] s_axis_tuser_threshold,
  input  logic        s_axis_tuser_evaluated,
  input  logic        s_axis_tuser_detected,
  input  logic [1:0]  s_axis_tuser_pfa_select,
  input  logic        s_axis_tuser_evaluate_center,
  output logic        m_axis_tvalid,
  input  logic        m_axis_tready,
  output logic [57:0] m_axis_tdata,
  output logic        m_axis_tlast,
  output logic [11:0] m_axis_tuser_start_shifted_bin,
  output logic [11:0] m_axis_tuser_end_shifted_bin,
  output logic [11:0] m_axis_tuser_peak_shifted_bin,
  output logic [11:0] m_axis_tuser_coarse_span_bins,
  output logic [57:0] m_axis_tuser_noise,
  output logic [61:0] m_axis_tuser_threshold,
  output logic [1:0]  m_axis_tuser_pfa_select,
  output logic        m_axis_tuser_evaluate_center,
  output logic        m_axis_tuser_candidate_valid,
  output logic        status_frame_error_sticky,
  output logic        status_candidate_overflow_sticky
);
  axis_candidate_grouping grouping_i (.*);
endmodule
