"""Bit-exact integer references for synthesizable PHASE-06 RTL."""

from .frame_stats import (
    ENERGY_WIDTH,
    ERROR_EARLY_TLAST,
    ERROR_MISSING_TLAST,
    ERROR_NONE,
    FRAME_LENGTH,
    INDEX_WIDTH,
    POWER_WIDTH,
    SAMPLE_COUNT_WIDTH,
    AxisFrameStatsModel,
    FrameStatsResult,
    frame_stats,
    pack_ci8_bytes,
    sample_power,
    unpack_ci8_word,
)
from .hann_window import (
    COEFFICIENT_FRACTION_BITS,
    COEFFICIENT_SCALE,
    COEFFICIENT_WIDTH,
    OUTPUT_COMPONENT_WIDTH,
    OUTPUT_FRACTION_BITS,
    OUTPUT_WORD_WIDTH,
    PRODUCT_WIDTH,
    build_word_length_study,
    coefficient_for_index,
    pack_windowed_word,
    quantized_hann_coefficients,
    round_shift_away_from_zero,
    unpack_windowed_word,
    window_component,
    window_frame,
    window_word,
)
from .fft_model import (
    architecture_decision_study,
    build_numerical_study,
    quantized_unscaled_fft,
    selected_ip_configuration,
    sign_extend_input_word,
    unpack_fft_word,
)
from .fft_power import (
    COMPONENT_MAX as FFT_POWER_COMPONENT_MAX,
    COMPONENT_MIN as FFT_POWER_COMPONENT_MIN,
    POWER_FRACTION_BITS as FFT_POWER_FRACTION_BITS,
    POWER_MAX_REACHABLE as FFT_POWER_MAX_REACHABLE,
    POWER_WIDTH as FFT_POWER_WIDTH,
    SQUARE_WIDTH as FFT_POWER_SQUARE_WIDTH,
    linear_power,
    pack_fft_word as pack_fft_power_input_word,
    power_from_fft_word,
    power_real_value,
    unpack_fft_word as unpack_fft_power_input_word,
    width_proof as fft_power_width_proof,
)

__all__ = [
    "ENERGY_WIDTH",
    "ERROR_EARLY_TLAST",
    "ERROR_MISSING_TLAST",
    "ERROR_NONE",
    "FRAME_LENGTH",
    "INDEX_WIDTH",
    "POWER_WIDTH",
    "SAMPLE_COUNT_WIDTH",
    "AxisFrameStatsModel",
    "FrameStatsResult",
    "frame_stats",
    "pack_ci8_bytes",
    "sample_power",
    "unpack_ci8_word",
    "COEFFICIENT_FRACTION_BITS",
    "COEFFICIENT_SCALE",
    "COEFFICIENT_WIDTH",
    "OUTPUT_COMPONENT_WIDTH",
    "OUTPUT_FRACTION_BITS",
    "OUTPUT_WORD_WIDTH",
    "PRODUCT_WIDTH",
    "build_word_length_study",
    "coefficient_for_index",
    "pack_windowed_word",
    "quantized_hann_coefficients",
    "round_shift_away_from_zero",
    "unpack_windowed_word",
    "window_component",
    "window_frame",
    "window_word",
    "architecture_decision_study",
    "build_numerical_study",
    "quantized_unscaled_fft",
    "selected_ip_configuration",
    "sign_extend_input_word",
    "unpack_fft_word",
    "FFT_POWER_COMPONENT_MAX",
    "FFT_POWER_COMPONENT_MIN",
    "FFT_POWER_FRACTION_BITS",
    "FFT_POWER_MAX_REACHABLE",
    "FFT_POWER_WIDTH",
    "FFT_POWER_SQUARE_WIDTH",
    "linear_power",
    "pack_fft_power_input_word",
    "power_from_fft_word",
    "power_real_value",
    "unpack_fft_power_input_word",
    "fft_power_width_proof",
]
