"""PHASE-04 core parameter extraction reference API."""

from .classification import FEATURE_HISTORY_BYTES, FeatureHistoryStore, classify_features
from .evaluation import characterize_phase04_r2_oos, evaluate_parameter_methods, evaluate_phase04_r2
from .extraction import (
    ANALYSIS_METHODS,
    BANDWIDTH_METHODS,
    POWER_SNR_METHODS,
    NOISE_METHODS,
    R2_BAND_HISTORY_BYTES,
    R2_PARAMETER_HISTORY_BYTES,
    BandEdgeHistoryStore,
    MethodSelection,
    ParameterExtractor,
    build_analysis_candidates,
    compute_transient_guard,
    estimate_band_support,
    extract_frame_features,
)
from .models import (
    AnalysisCandidate,
    BandSupportResult,
    BandwidthEstimate,
    EventParameterEstimate,
    FieldState,
    FrequencyEstimate,
    ParameterFrameResult,
    ParameterInvalidReason,
    RelativePowerEstimate,
    SignalDomainEstimate,
)
from .scenes import ParameterSceneFrame, generate_parameter_scene, load_parameter_catalog
from .operator_assisted import (
    AnalysisSpan,
    FieldMeasurement,
    MeasurementCandidate,
    MeasurementContext,
    MeasurementIntent,
    MeasurementQuality,
    OperatorAssistedParameterResult,
    OperatorMeasurementProcessor,
    project_to_simplex,
    suggest_analysis_span,
)
from .r2 import (
    HANN_CORRECTION,
    MORPHOLOGY_MOMENT_THRESHOLD,
    NOMINAL_GROW_RATIO,
    NOMINAL_SEED_RATIO,
    build_method_lock,
    hann_covariance_calibration,
    hann_end_to_end_calibration,
    iid_trimmed_mean_expectation,
    morphology_calibration,
)

__all__ = [
    "ANALYSIS_METHODS",
    "AnalysisCandidate",
    "BANDWIDTH_METHODS",
    "BandEdgeHistoryStore",
    "BandSupportResult",
    "BandwidthEstimate",
    "EventParameterEstimate",
    "FEATURE_HISTORY_BYTES",
    "FeatureHistoryStore",
    "FieldState",
    "FrequencyEstimate",
    "MethodSelection",
    "NOISE_METHODS",
    "POWER_SNR_METHODS",
    "R2_BAND_HISTORY_BYTES",
    "R2_PARAMETER_HISTORY_BYTES",
    "ParameterExtractor",
    "ParameterFrameResult",
    "ParameterInvalidReason",
    "ParameterSceneFrame",
    "AnalysisSpan",
    "FieldMeasurement",
    "MeasurementCandidate",
    "MeasurementContext",
    "MeasurementIntent",
    "MeasurementQuality",
    "OperatorAssistedParameterResult",
    "OperatorMeasurementProcessor",
    "project_to_simplex",
    "suggest_analysis_span",
    "RelativePowerEstimate",
    "SignalDomainEstimate",
    "classify_features",
    "build_analysis_candidates",
    "compute_transient_guard",
    "characterize_phase04_r2_oos",
    "evaluate_parameter_methods",
    "evaluate_phase04_r2",
    "estimate_band_support",
    "extract_frame_features",
    "generate_parameter_scene",
    "load_parameter_catalog",
    "HANN_CORRECTION",
    "MORPHOLOGY_MOMENT_THRESHOLD",
    "NOMINAL_GROW_RATIO",
    "NOMINAL_SEED_RATIO",
    "build_method_lock",
    "hann_covariance_calibration",
    "hann_end_to_end_calibration",
    "iid_trimmed_mean_expectation",
    "morphology_calibration",
]
